### ISSUE TITLE
I think fish spawning might be a little bugged.

### ISSUE THREAD

**Issue by brisingraerowing** [frikinzi/frikinzis_fauna#2]
![2021-12-24_18 07 32](https://user-images.githubusercontent.com/250409/147373952-b2ee131d-49b6-4f1b-8148-29d346f17c74.png)

FF 1.2.1

Might be another mod screwing things up as well.

**Comment by frikinzi** [comment]
Unfortunately that's a common issue with water mob spawnings in general in 1.12.2, seen in a lot of other mods with water creatures too. It looks to be a Minecraft issue. I would suggest lowering spawn rates in the configuration file, or disabling their spawning altogether.

**Comment by frikinzi** [comment]
Tried to fix this issue in the new update. let me know if they still mass spawn
