### ISSUE TITLE
Ideas: FeatherCraft tribute

### ISSUE THREAD

**Issue by HatcheryRoosters** [frikinzi/frikinzis_fauna#3]
Since FeatherCraft will never see the light of day, I think it would be nice to give the birds a second chance (mainly the geese, ducks, muscovies and swans) I have the images for reference

If the males and females share textures, make the males bigger than the females.

![Ducks](https://user-images.githubusercontent.com/36781707/147374646-ce06853d-5940-43c3-b95b-1ce456735777.png)
Since the mod has it's own Wild and Wood ducks, maybe you could just add the Pekins.

![Geese_](https://user-images.githubusercontent.com/36781707/147374703-517bf0c2-a51f-469f-9ef1-889db63a8677.png)
All the geese but the Chinese goose have the same model, you can reuse the model and save a lot of time, leaving just the textures to be replicated.

Male turkeys have the same models, and so do the females
![Turkey_Preview](https://user-images.githubusercontent.com/36781707/147374716-3b720f8e-73ba-45bd-b299-962d8618ae22.png)

It would be nice to see these be added in the future

**Comment by frikinzi** [comment]
Hello! Thanks for your suggestions. Please post them in the discord channel in the future. link is on the curseforge page. :)

**Comment by HatcheryRoosters** [comment]
No problem, I hope you can successfully replicate the models and textures!
