### ISSUE TITLE
Male birds give birth

### ISSUE THREAD

**Issue by HatcheryRoosters** [frikinzi/frikinzis_fauna#7]
Male birds drop chicks when they are not supposed to, this happens with any bird

How to replicate: Take a bird and breed a male and female
![2022-03-18_16 23 30](https://user-images.githubusercontent.com/36781707/159078187-eeab8feb-a587-46c4-827c-eb0b8365f0d8.png)

**Comment by frikinzi** [comment]
Fixed in 1.4.0-1.16.5
